### ISSUE TITLE
Media sections in answer do not match offer

### ISSUE THREAD

**Issue by markblumenau** [skymaze/pymediasoup#5]
Hello! 
Trying to run the example code I get the following error from aiortc:
ValueError: Media sections in answer do not match offer 
Not sure what exactly causes this problem, but maybe it is possible to find what is wrong. 
Thanks in advance!

**Comment by neilyoung** [comment]
I ran into the same issue, which might not be one for you anymore. I came across this, when I subscribed to an audio stream, unsubscribed and later subscribed to a video stream. I could narrow down this to some point, but it seems, that the consumer joins a stale RTP stream, that's why it forms an answer, which doesn't match the offered media...

But I couldn't solve this. If I always stick with the same media type, that problem doesn't happen

**Comment by neilyoung** [comment]
Oh, a second after my first post I think I found the answer. The reason is the attempt to recycle some old "closedMediaSections". 

https://github.com/skymaze/pymediasoup/blob/6fd3564ed690fe59ab886334fe136bca84648a7e/pymediasoup/handlers/sdp/remote_sdp.py#L169

See, if you can comment 170 to 173 and if this solves your problem.

**Comment by markblumenau** [comment]
Thanks!
However, it has been a while since I moved from that project, so I guess it's best to close this issue.

**Comment by neilyoung** [comment]
May I ask what you did choose in replacement?

**Comment by markblumenau** [comment]
In my case Jitsi with some minor changes worked just fine

**Comment by neilyoung** [comment]
So you dropped MediaSoup, I guess? I'm pretty happy with that (replaced Kurento Media Server). Having clients for Web, Android and now for Python. Thanks for the details. Have a nice weekend.

BTW: This lib is pretty good, though

**Comment by markblumenau** [comment]
Yep, dropped mediasoup. This lib is good, that's true.
Have a nice weekend.
